version: "2"

run:
  concurrency: 4
  issues-exit-code: 1
  tests: true

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - errorlint
    - bodyclose
    - sqlclosecheck
    - ineffassign
    - unused
    - copyloopvar
    - contextcheck
    - gosec
    - misspell
    - unparam
    - errname
    - nakedret
    - goprintffuncname
    - paralleltest
    - funlen
    - gocognit
    - gocritic
    - goconst

  settings:
    errcheck:
      check-type-assertions: false
      check-blank: false

    funlen:
      lines: 80
      statements: 40

    gocognit:
      min-complexity: 30

    goconst:
      min-len: 3
      min-occurrences: 3

    nakedret:
      max-func-lines: 30

    unparam:
      check-exported: false

    misspell:
      locale: US

    gocritic:
      enabled-tags:
        - performance
      settings:
        captLocal:
          paramsOnly: true
        rangeValCopy:
          sizeThreshold: 32
          skipTestFuncs: true

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
