name: CI

on:
  push:
    branches:
      - main
      - 'feat/**'
      - 'fix/**'
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: read

jobs:
  backend:
    name: Go Test and Lint
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || github.event_name == 'push'

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.2'
          cache: true

      - name: Run tests
        run: go test -v -race ./...

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest
          args: --timeout=5m
          skip-cache: true

  frontend:
    name: Frontend Lint and Build
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'push' || github.event_name == 'pull_request'
    defaults:
      run:
        working-directory: web
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'web/package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

    # Only trigger this job if frontend files changed
    # You can keep this check or move it to top-level "on.paths"
    outputs:
      frontend_changed: ${{ steps.filter.outputs.changed }}
